### ISSUE TITLE
Release of Unity.Container 5.9.2.797 broke asp.net core app

### ISSUE THREAD

**Issue by ChristophWeigert** [unitycontainer/microsoft-dependency-injection#36]
Der Typ "Unity.UnityContainerExtensions" in der Assembly "Unity.Container, Version=5.9.2.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0" konnte nicht geladen werden.'

I think the bug was introduced with this commit:
https://github.com/unitycontainer/container/commit/ea7a4b32876750a86ee1036f4e66925215a0c2eb#diff-0b8dacf1c9d391b33621c2aa2cd31439

**Comment by schoeffj** [comment]
@ENikS `Unity.Microsoft.DependencyInjection.Configuration.AddServices(IUnityContainer container, IServiceCollection services)` uses the extension method `Configure<MdiExtension>()`.
While compiling Unity.Microsoft.DependencyInjection v5.9.0 this extension method was located in class `Unity.UnityContainerExtensions`.
With Unity.Container v5.9.2 this class was renamed to `Unity.ExtensionExtensions`, but Unity.Microsoft.DependencyInjection v5.9.0 still expects the extension method in `Unity.UnityContainerExtensions`, because it was compiled with Unity.Container v5.9.0.

Please provide a new version of Unity.Microsoft.DependencyInjection that explicitly uses Unity.Container v5.9.2 or higher.

### To Reproduce

```
dotnet new webapi -n UnityMsDI
dotnet add UnityMsDI/UnityMsDI.csproj package Unity.Microsoft.DependencyInjection -v 5.9.0
dotnet add UnityMsDI/UnityMsDI.csproj package Unity.Container -v 5.9.2
```

Add `using Unity.Microsoft.DependencyInjection;` and `.UseUnityServiceProvider()` to `UnityMsDI/Program.cs`.

`dotnet run -p ./UnityMsDI/UnityMsDI.csproj` results in

```
Unhandled Exception: System.TypeLoadException: Could not load type 'Unity.UnityContainerExtensions' from assembly 'Unity.Container, Version=5.9.2.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0'.
   at Unity.Microsoft.DependencyInjection.Configuration.AddServices(IUnityContainer container, IServiceCollection services)
   at Unity.Microsoft.DependencyInjection.ServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.<Build>g__GetProviderFromFactory|13_0(IServiceCollection collection)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at UnityMsDI.Program.Main(String[] args) in ..\UnityMsDI\Program.cs:line 18
```

**Comment by karelkral** [comment]
Please provide a new version of Unity.Microsoft.DependencyInjection that explicitly uses Unity.Container v5.9.2 or higher. I cannot use this package with Unity 5.9.3
