### ISSUE TITLE
Unity Container no longer Resolving dependency to Ilog for custom Selected Controllers

### ISSUE THREAD

**Issue by vllama** [unitycontainer/microsoft-dependency-injection#43]
### Description

Since Upgrading to 5.10.3 from 5.8.13
 Unity cannot resolve any webapi controllers that take an ILogger as a constructor parameter.

We configure logging as follows:
```C#
  container.AddExtension(new LoggingExtension(loggerFactory));
```

We have a custom IHttpControllerSelector implementation for some controllers.
using 
```C#
config.Services.Replace( typeof(IHttpControllerSelector),  new OurCustomControllerSelector(config, _logger));
```
Unity cannot resolve any of the controller types returned by a custom controller selector.
If we bypass this and use a hard coded rout route to any of these controllers, it is able to resolve them.
As well if we add a constructor without ILogger it resolves without issue.

### To Reproduce

Will take some time to extract a poc out of our code base.

**Additional context**
This has worked well with many previous versions of unity.

**Comment by ENikS** [comment]
Feel free to reopen if you decide to provide failing test case so I could fix it

**Comment by Jeromino** [comment]
I also came across similar issues. The actual exception was not provided with this issue so we can't guess what is the problem that may not be related to what I came across but I resolved a similar problem by specifying the constructor to use in order to avoid an ambiguous constructor exception:

`container.RegisterType<ILoggerFactory, LoggerFactory>(new ContainerControlledLifetimeManager(),
                new InjectionConstructor(new ResolvedParameter<IEnumerable<ILoggerProvider>>()));`
